"""Rename plateNumber to plate_number in Car

Revision ID: cee61dd40002
Revises: 161fc60d584e
Create Date: 2025-07-25 12:25:31.517631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee61dd40002'
down_revision: Union[str, Sequence[str], None] = '161fc60d584e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('plate_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'plate_number')
    # ### end Alembic commands ###
